server:
  port: 8080

spring:
  application:
    name: API-gateway

  cloud:
    gateway:

      globalcors:

        corsConfigurations:
          '[/**]':
            allowed-origins:
              "http://localhost:5173"      # React app
            allowedMethods:
             "*"
            allowedHeaders:
             "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**


jwt:
  secret: "my_super_secret_key_1234567890123456"