server:
  port: 8081   # AuthService chạy ở port 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:file:./data/userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console   # Truy cập: http://localhost:8081/h2-console

jwt:
  secret: mysecretkey1234567890   # dùng để ký JWT
  expiration: 86400000            # 1 ngày (ms)